#! /bin/sh

###################################
#            АВТОСТАРТ            #
###################################

sxhkd &
picom &
polybar top &
xsetroot -cursor_name left_ptr & # Нормальный курсор
# nitrogen --restore &

###################################
#           ВОРКСПЕЙСЫ            #
###################################

# Объявление воркспейсов
bspc monitor -d 1 2 3 4 5 6 7

# Правила окон
# bspc rule -a firefox desktop='^2'
# bspc rule -a telegram-desktop desktop = '^10'

###################################
#            ДЕКОРАЦИИ            #
###################################

# Рамки и отступы
bspc config border_width        10
bspc config window_gap          20

# Цвета
bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"		# Цвет выбора нового положения окна

# Коэффициент разделения, сколько процентов останется 
# от родительского окна при открытии нового
bspc config split_ratio          0.5

bspc config focus_follows_pointer true	# Фокус окна при наведении курсора
bspc config pointer_modifier	super

# Рамки/гапсы/паддинги если открыто только 1 окно
bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
